name: GitHub Actions Deploy WebSite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build Project
        run: |
          ng build --prod --output-path docs
          cp necessary/ docs/
          rm -rf !(docs)
          cp docs/* /
