name: GitHub Actions Deploy WebSite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
              node-version: 12.8
              
      - name: Install angular CLI 
        run: npm install -g @angular/cli
          
      - name: npm dependencies
        run: npm install 
         
      # Runs a set of commands using the runners shell
      - name: Build
        run: ng build --prod --output-path docs
 
      # Runs a set of commands using the runners shell
      - name: File storage
        run: |
          cp -a necessary/. docs/
          rm -rf !(docs)
          cp docs/. ./
